# Generated by Django 5.0.7 on 2024-10-08 15:47

import froala_editor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Глава")),
                ("text", froala_editor.fields.FroalaField(verbose_name="Текст")),
                (
                    "slug",
                    models.SlugField(
                        help_text="это поле заполняется автоматически",
                        max_length=255,
                        unique=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "date_add",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "date_update",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
            ],
            options={
                "verbose_name": "Книга знаний",
                "verbose_name_plural": "Книга знаний",
            },
        ),
    ]
