# Generated by Django 5.0.7 on 2024-10-09 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="Текст ответа")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Порядок ответа"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ",
                "verbose_name_plural": "Ответы",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=255, verbose_name="Текст вопроса"),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
            },
        ),
        migrations.CreateModel(
            name="PsychoProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Завершен"),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_psy_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Игрок",
                    ),
                ),
                (
                    "selected_answers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="player_answers",
                        to="psychologist.answer",
                        verbose_name="Выбранные ответы",
                    ),
                ),
                (
                    "asked_questions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="asked_by_players",
                        to="psychologist.question",
                        verbose_name="Заданные вопросы",
                    ),
                ),
                (
                    "current_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="psychologist.question",
                        verbose_name="Текущий вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс игрока",
                "verbose_name_plural": "Прогрессы игроков",
            },
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="psychologist.question",
                verbose_name="Вопрос",
            ),
        ),
        migrations.CreateModel(
            name="QuestionTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_question_transition",
                        to="psychologist.answer",
                        verbose_name="Ответ",
                    ),
                ),
                (
                    "next_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_questions",
                        to="psychologist.question",
                        verbose_name="Следующий вопрос",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="psychologist.question",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Переход между вопросами",
                "verbose_name_plural": "Переходы между вопросами",
            },
        ),
        migrations.AddConstraint(
            model_name="psychoprogress",
            constraint=models.UniqueConstraint(
                condition=models.Q(("completed", False)),
                fields=("player",),
                name="unique_active_progress",
            ),
        ),
    ]
