# Generated by Django 5.0.7 on 2024-10-09 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("psychologist", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("question", "order")},
        ),
    ]
