# Generated by Django 5.0.7 on 2024-10-08 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                ("description", models.TextField(default="", verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предметы",
            },
        ),
        migrations.AddField(
            model_name="player",
            name="date_of_change",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата изменения аккаунта"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="temporary_password",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Временный пароль"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="temporary_password_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время создания временного пароля"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="email",
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="training_check",
            field=models.BooleanField(default=False, verbose_name="Обучение"),
        ),
        migrations.AlterField(
            model_name="player",
            name="username",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Имя пользователя"
            ),
        ),
        migrations.CreateModel(
            name="Backpack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Игрок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рюкзак",
                "verbose_name_plural": "Рюкзаки",
            },
        ),
        migrations.CreateModel(
            name="BackpackItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backpack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_app.backpack",
                        verbose_name="Рюкзак",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_app.item",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предмет рюкзака",
                "verbose_name_plural": "Предметы рюкзака",
            },
        ),
    ]
