# Generated by Django 5.0.7 on 2024-10-08 15:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Игра сотрудником"),
                ),
            ],
            options={
                "verbose_name": "Игра сотрудником",
                "verbose_name_plural": "Игра сотрудником",
            },
        ),
        migrations.CreateModel(
            name="MiniGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название игры"),
                ),
            ],
            options={
                "verbose_name": "Мини-игра",
                "verbose_name_plural": "Мини-игры",
            },
        ),
        migrations.CreateModel(
            name="MiniNovella",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название новеллы"),
                ),
            ],
            options={
                "verbose_name": "Мини-новелла",
                "verbose_name_plural": "Мини-новеллы",
            },
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название подарка"),
                ),
            ],
            options={
                "verbose_name": "Подарок",
                "verbose_name_plural": "Подарки",
            },
        ),
        migrations.CreateModel(
            name="PlayerProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "errors",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Совершенные ошибки"
                    ),
                ),
                (
                    "experience_gained",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Полученный опыт"
                    ),
                ),
                (
                    "completion_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Время завершения",
                    ),
                ),
                (
                    "employee",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="mini_location_app.employeegame",
                        verbose_name="Игра сотрудником",
                    ),
                ),
                (
                    "game",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="mini_location_app.minigame",
                        verbose_name="Мини-игра",
                    ),
                ),
                (
                    "novella",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="mini_location_app.mininovella",
                        verbose_name="Мини-новелла",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Игрок",
                    ),
                ),
                (
                    "reward",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="mini_location_app.reward",
                        verbose_name="Полученный подарок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс игрока",
                "verbose_name_plural": "Прогресс игроков",
            },
        ),
    ]
