# Generated by Django 5.0.7 on 2024-10-09 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mini_location_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerprogress",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="playerprogress",
            name="errors",
        ),
        migrations.RemoveField(
            model_name="playerprogress",
            name="game",
        ),
        migrations.RemoveField(
            model_name="playerprogress",
            name="novella",
        ),
        migrations.RemoveField(
            model_name="playerprogress",
            name="reward",
        ),
        migrations.CreateModel(
            name="PlayerEmployeeGameProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mini_location_app.employeegame",
                        verbose_name="Игра сотрудником",
                    ),
                ),
                (
                    "player_progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_game_progress",
                        to="mini_location_app.playerprogress",
                        verbose_name="Прогресс игрока",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс игрока по игре сотрудником",
                "verbose_name_plural": "Прогресс игрока по играм сотрудниками",
            },
        ),
        migrations.CreateModel(
            name="PlayerGameProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mini_location_app.minigame",
                        verbose_name="Мини-игра",
                    ),
                ),
                (
                    "player_progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_progress",
                        to="mini_location_app.playerprogress",
                        verbose_name="Прогресс игрока",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс игрока по игре",
                "verbose_name_plural": "Прогресс игрока по играм",
            },
        ),
        migrations.CreateModel(
            name="PlayerNovellaProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "novella",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mini_location_app.mininovella",
                        verbose_name="Мини-новелла",
                    ),
                ),
                (
                    "player_progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="novella_progress",
                        to="mini_location_app.playerprogress",
                        verbose_name="Прогресс игрока",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс игрока по новелле",
                "verbose_name_plural": "Прогресс игрока по новеллам",
            },
        ),
        migrations.CreateModel(
            name="PlayerRewardProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_progress",
                        to="mini_location_app.playerprogress",
                        verbose_name="Прогресс игрока",
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mini_location_app.reward",
                        verbose_name="Подарок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс игрока по подаркам",
                "verbose_name_plural": "Прогресс игрока по подаркам",
            },
        ),
    ]
